### ISSUE TITLE
Consider adding Infostealers.com source

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [EndlessFractal/Threat-Intel-Feed#5]
The all-around Infostealers hub (by Hudson Rock) with reports and recent news about Infostealing malware
Link: https://www.infostealers.com/

**Comment by EndlessFractal** [comment]
Hello! I recently visited your page and noticed that the two RSS feeds provided are currently returning no content:
- https://www.infostealers.com/feed/
- https://www.infostealers.com/comments/feed/

Additionally, I saw three more links to feeds at the bottom of the page:
- https://www.infostealers.com/learn-info-stealers/feed
- https://www.infostealers.com/info-stealers-reports/feed
- https://www.infostealers.com/info-stealers-techniques/feed

Perhaps it is a good idea to update the links to ensure a better UX.

I'm considering adding it in the future.

Regards!

**Comment by hudsonrock-partnerships** [comment]
@EndlessFractal Thank you very much for the comment. 
This is the current feed that we suggest using for recent articles/news: https://www.infostealers.com/learn-info-stealers/feed/

**Comment by hudsonrock-partnerships** [comment]
Suggested via PR
